name: Deploy Arrively Rust App

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: arrively-artifact
          path: target/release/arrively-project-main 

  

  deploy-to-ec2:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: arrively-artifact
          path: .

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ubuntu
          EC2_HOST: 13.60.21.29  
        run: |
          echo "$SSH_PRIVATE_KEY" > my-ec2-keypair.pem
          chmod 600 my-ec2-keypair.pem
          
          
          export SSH_OPTS="-o StrictHostKeyChecking=no"

          
          scp -i my-ec2-keypair.pem $SSH_OPTS arrively-project-main $EC2_USER@$EC2_HOST:/mnt/arrively-project/Arrively-project-main/
          
          
          ssh -i my-ec2-keypair.pem $SSH_OPTS $EC2_USER@$EC2_HOST <<EOF
            sudo systemctl restart arrively.service
          EOF

